name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  actions: read
  issues: read
  deployments: write
  pull_requests: write

jobs:
  publish-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Set up .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.version }} --no-commit-hooks --no-git-tag-version
        git add package.json package-lock.json
        git commit -m "chore: bump version to ${{ github.event.inputs.version }}"

    - name: Create and checkout a temporary branch
      run: |
        BRANCH_NAME="publish-${{ github.event.inputs.version }}"
        git checkout -b $BRANCH_NAME

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Publish to NPM
      run: npm publish

    - name: Push changes and tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="publish-${{ github.event.inputs.version }}"
        git tag v$(node -p "require('./package.json').version")
        git push origin $BRANCH_NAME
        git push origin --tags

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const branchName = `publish-${context.payload.inputs.version}`;
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Publish version ${context.payload.inputs.version}`,
            head: branchName,
            base: 'main',
          });
          console.log(`Pull request created: ${pullRequest.html_url}`);
