name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      issues: read
      pull-requests: write
      deployments: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
  
    - name: Set up .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.version }} --no-commit-hooks --no-git-tag-version
        git add package.json package-lock.json

    - name: Create feature branch
      run: |
        git checkout -b bump-version-${{ github.event.inputs.version }}

    - name: Commit changes
      run: |
        git commit -m "chore: bump version to ${{ github.event.inputs.version }}"

    - name: Push changes
      run: |
        git push --set-upstream origin bump-version-${{ github.event.inputs.version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create pull request
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Bump version to ${{ github.event.inputs.version }}`,
            head: `bump-version-${{ github.event.inputs.version }}`,
            base: 'master',
            body: `This pull request bumps the version to ${{ github.event.inputs.version }}.`
          });
          console.log(`Created pull request #${pullRequest.number}`);

    - name: Push tags
      run: |
        git tag v$(node -p "require('./package.json').version")
        git push origin --tags
